animes = [
["Attack on Titan"],
["BORUTO: NARUTO NEXT GENERATIONS"],
["Haikyu!!"],
["Fire Force"],
["Sword Art Online"],
["Rent-a-Girlfriend"],
["The Misfit of Demon King Academy"],
["Black Clover"],
["Hunter x Hunter"],
["The God of High School"],
["Monster Girl Doctor"],
["Shokugeki no Soma"],
["Naruto Shippuden"],
["One Piece"],
["Re:ZERO -Starting Life in Another World-"],
["Demon Slayer: Kimetsu no Yaiba"],
["My Hero Academia"],
["My Teen Romantic Comedy SNAFU"],
["That Time I Got Reincarnated as a Slime"],
["Dr. STONE"],
]