animes = [
["Rent-a-Girlfriend"],
["Fire Force"],
["One Piece"],
["The God of High School"],
["That Time I Got Reincarnated as a Slime"],
["Demon Slayer: Kimetsu no Yaiba"],
["Hunter x Hunter"],
["Haikyu!!"],
["Shokugeki no Soma"],
["Black Clover"],
["Sword Art Online"],
["My Teen Romantic Comedy SNAFU"],
["Re:ZERO -Starting Life in Another World-"],
["Dr. STONE"],
["BORUTO: NARUTO NEXT GENERATIONS"],
["Naruto Shippuden"],
["Monster Girl Doctor"],
["Attack on Titan"],
["The Misfit of Demon King Academy"],
["Digimon Adventure: (2020)"],
["Naruto"],
]