animes = [
["Hunter x Hunter"],
["The God of High School"],
["Attack on Titan Season 2"],
["Re:ZERO -Starting Life in Another World- (English Dub)"],
["Food Wars! The Fifth Plate"],
["Black Clover"],
["Re:ZERO -Starting Life in Another World- Season 2"],
["BORUTO: NARUTO NEXT GENERATIONS"],
["Fire Force Season 2"],
["Rent-a-Girlfriend"],
["Monster Girl Doctor"],
["HAIKYU!! 3rd Season"],
["Attack on Titan Season 3"],
["The Misfit of Demon King Academy"],
["Shadowverse"],
["One Piece: WANO KUNI (892-Current)"],
["The Rising of the Shield Hero"],
["My Hero Academia Season 4"],
["The God of High School (English Dub)"],
["Demon Slayer: Kimetsu no Yaiba"],
["Naruto Shippuden: The Kazekage's Rescue"],
["That Time I Got Reincarnated as a Slime"],
["Attack on Titan"],
["My Teen Romantic Comedy SNAFU Climax!"],
["Naruto Season 1"],
["DARLING in the FRANXX"],
["HAIKYU‼ TO THE TOP"],
]