animes = [
["Re:ZERO -Starting Life in Another World- Season 2"],
["The God of High School"],
["Dr. STONE"],
["Hunter x Hunter"],
["GIBIATE"],
["Rent-a-Girlfriend"],
["Black Clover"],
["That Time I Got Reincarnated as a Slime"],
["Attack on Titan Season 3"],
["Attack on Titan"],
["One Piece: WANO KUNI (892-Current)"],
["The Misfit of Demon King Academy"],
["BORUTO: NARUTO NEXT GENERATIONS"],
["Fire Force Season 2"],
["HAIKYU‼ TO THE TOP"],
["HAIKYU!! 3rd Season"],
["BURN THE WITCH"],
["Re:ZERO -Starting Life in Another World- (English Dub)"],
["Food Wars! The Fifth Plate"],
["Ahiru no Sora"],
["My Hero Academia Season 4"],
["Re:ZERO -Starting Life in Another World- Season 2 (English Dub)"],
["Demon Slayer: Kimetsu no Yaiba"],
["My Teen Romantic Comedy SNAFU Climax!"],
["Monster Girl Doctor"],
["Naruto Season 1"],
["The Rising of the Shield Hero (English Dub)"],
]