animes = [
["Attack on Titan Season 2"],
["Re:ZERO -Starting Life in Another World- Season 2"],
["Monster Girl Doctor"],
["One Piece: WANO KUNI (892-Current)"],
["Attack on Titan Season 3"],
["Black Clover"],
["Sword Art Online Alicization War of Underworld"],
["The God of High School"],
["Demon Slayer: Kimetsu no Yaiba"],
["HAIKYU‼ TO THE TOP"],
["Fire Force"],
["The Misfit of Demon King Academy"],
["BORUTO: NARUTO NEXT GENERATIONS"],
["Fire Force Season 2"],
["Hunter x Hunter"],
["Food Wars! The Fifth Plate"],
["HAIKYU!! 3rd Season"],
["Rent-a-Girlfriend"],
["Dr. STONE"],
["That Time I Got Reincarnated as a Slime"],
["Naruto Shippuden: The Two Saviors"],
["My Hero Academia Season 4"],
["Attack on Titan"],
["The God of High School (English Dub)"],
]